### ISSUE TITLE
画面错误

### ISSUE THREAD

**Issue by feliciaifu** [MapleRecall/reshade-FFXIV-EnhancedGamePlay#1]
显卡：AMD RX 7900XTX 最新驱动
未对预设进行任何更改，全新安装Reshade
问题：
Glamayre_Fast_Effects.fx在俯视视角下画面上部缺失
![屏幕截图 2023-08-17 172328](https://github.com/MapleRecall/reshade-FFXIV-EnhancedGamePlay/assets/93038930/6638a57e-7d96-4222-91ea-5ffc81dd3bde)
![屏幕截图 2023-08-17 172144](https://github.com/MapleRecall/reshade-FFXIV-EnhancedGamePlay/assets/93038930/a1a3c25a-4fac-4c40-96c2-7f8789e842b5)
水平视角正常
![屏幕截图 2023-08-17 172400](https://github.com/MapleRecall/reshade-FFXIV-EnhancedGamePlay/assets/93038930/954db104-1bce-446d-b681-b74516ed074f)
关闭Glamayre_Fast_Effects.fx画面不再缺失
![屏幕截图 2023-08-17 173651](https://github.com/MapleRecall/reshade-FFXIV-EnhancedGamePlay/assets/93038930/1a45a727-6578-4e28-8703-e3113dcc36d5)
PPFX_SSDO_X.fx造成画面过亮
![屏幕截图 2023-08-17 172953](https://github.com/MapleRecall/reshade-FFXIV-EnhancedGamePlay/assets/93038930/4c03dc34-423a-44a8-8028-d5a2b05601aa)
关闭所有的PPFX_SSDO_X.fx后画面亮度正常
![屏幕截图 2023-08-17 174008](https://github.com/MapleRecall/reshade-FFXIV-EnhancedGamePlay/assets/93038930/b845b1ab-a4e1-4a49-90f1-13e24c5efc5a)
这两个效果与AMD显卡可能存在兼容性问题

**Comment by MapleRecall** [comment]
好怪，你的主页里好多effects都有两份……有可能是重复添加了？有些时候这会造成一些诡异的问题，尤其是有基于前后帧分析的，因为texture是共享的。一般来说这些效果不应该有硬件上导致的差异

**Comment by feliciaifu** [comment]
> 好怪，你的主页里好多effects都有两份……有可能是重复添加了？有些时候这会造成一些诡异的问题，尤其是有基于前后帧分析的，因为texture是共享的。一般来说这些效果不应该有硬件上导致的差异

重新安装了Reshade，发现亮度问题是由重复造成的。
然后观察到画面缺失是由伪GI造成的
开启：
![屏幕截图 2023-08-17 181124](https://github.com/MapleRecall/reshade-FFXIV-EnhancedGamePlay/assets/93038930/8e1a58b1-436f-4cdf-90c5-eec3523487e1)
关闭：
![屏幕截图 2023-08-17 181405](https://github.com/MapleRecall/reshade-FFXIV-EnhancedGamePlay/assets/93038930/f4bb575a-09dd-4ebb-8d15-f21e61173cdb)
画面正常

**Comment by liuxd17thu** [comment]
在1200行附近，找到
```hlsl
sampler HBlurSampler {
    Texture = HBlurTex;
    AddressU = BORDER;
    AddressV = BORDER;
    AddressW = BORDER;
};

sampler VBlurSampler {
    Texture = VBlurTex;
    AddressU = BORDER;
    AddressV = BORDER;
    AddressW = BORDER;
};
```
删掉所有的`Address_ =  BORDER`;
